<?php

namespace Dada\CMSBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPageItems($page){
        $start = ($page-1)*$max;
        $max = $page*$max;
    }
}
