<?php

namespace Dada\CMSBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns page $page of Page
     * @param $page
     * @param $maxItems
     * @return array
     */
    public function getPageItems($page, $maxItems){
        $start = ($page-1)*$maxItems;
        $query = $this->createQueryBuilder('a')
            ->orderBy('a.created', 'desc')
            ->setFirstResult($start)
            ->setMaxResults($maxItems);
        return $query->getQuery()->getResult();
    }
}
